#!/bin/bash
# Post to Slack after a commit, with testing results
webhook_url="%slack_webhook%"
channel="%slack_channel%"

root=$(git rev-parse --show-toplevel)
cd $root
repo=$(basename $root)
user=$(git config --global --get user.name)
output=$(CODECLIMATE_REPO_TOKEN=%code_climate_token% bundle exec rake test:coverage)
git checkout public/coverage
rm -rf coverage
output=$(echo $output | sed 's/.*\(Finished tests in [0-9.]\+s, [0-9.]\+ tests\/s, [0-9.]\+ assertions\/s\.\).*[^0-9]\([0-9]\+ tests, .*\)/\1 *\2/g' | sed 's/Finished tests/executed tests/g')
output=$(echo $output | sed 's/Coverage.*(\([0-9.]\+%\)).*/(\1 code coverage)*/g')
output=$(echo $output | sed 's/Coverage = \([0-9.]\+%\).*/(\1 code coverage)*/g')
rev=$(git log -1 --format=format:%h)
ref=$(git rev-parse --abbrev-ref HEAD)
cd - >/dev/null
msg=$(echo "Build $rev of $repo/$ref by $user $output")
curl -X POST --data-urlencode "payload={\"channel\": \"$channel\", \"username\": \"Git CI\", \"text\": \"$msg\"}" $webhook_url
exit 0
